#!/usr/bin/env python3
"""Generate wire sizes/opcodes + fixed-request decode from x12_surface.xml.

ADR-0016/0018: XML is the source of truth. Complex requests (CreateSurface,
Present) keep hand validators in x12_surface.rs; fixed requests use
generated_decode.rs.
"""
from __future__ import annotations

import sys
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[3]
XML = ROOT / "proto/xcb/src/x12_surface.xml"
OUT_RS = ROOT / "safe/x12-proto/src/generated_wire.rs"
OUT_DECODE = ROOT / "safe/x12-proto/src/generated_decode.rs"
OUT_H = ROOT / "safe/x12-proto/include/x12_proto_generated.h"

TYPE_SIZE = {
    "CARD8": 1,
    "INT8": 1,
    "BYTE": 1,
    "BOOL": 1,
    "CARD16": 2,
    "INT16": 2,
    "CARD32": 4,
    "INT32": 4,
    "CARD64": 8,
    "INT64": 8,
    "WINDOW": 4,
    "DRAWABLE": 4,
    "SURFACE": 4,
    "SYNCOBJ": 4,
    "EVENT": 4,
    "ATOM": 4,
    "PIXMAP": 4,
}

# Fixed requests fully decoded from XML field layout (body, no header).
FIXED_DECODE = {
    "QueryVersion": [("major_version", "u32"), ("minor_version", "u32")],
    "QueryCapabilities": [("drawable", "u32")],
    "QueryModifiers": [("drawable", "u32"), ("format", "u32")],
    "DestroySurface": [("surface", "u32")],
    "ImportSyncobj": [("syncobj", "u32"), ("drawable", "u32")],
    "FreeSyncobj": [("syncobj", "u32")],
    "Attach": [("window", "u32"), ("surface", "u32")],
    "Detach": [("window", "u32")],
    "SelectInput": [("eid", "u32"), ("window", "u32"), ("event_mask", "u32")],
}


def align(n: int, a: int) -> int:
    return (n + a - 1) // a * a


def request_size(req: ET.Element) -> int:
    size = 4
    for child in list(req):
        tag = child.tag.split("}")[-1]
        if tag == "field":
            t = child.attrib["type"]
            sz = TYPE_SIZE.get(t, 4)
            if sz >= 2:
                size = align(size, min(sz, 4) if sz < 8 else 8)
            size += sz
        elif tag == "pad":
            size += int(child.attrib.get("bytes", 0))
        elif tag == "fd":
            pass
        elif tag == "list":
            pass
        elif tag == "required_start_align":
            a = int(child.attrib.get("align", 4))
            size = align(size, a)
    return align(size, 4)


def emit_decode_rs() -> str:
    lines = [
        "// @generated by safe/x12-proto/tools/gen_wire.py — do not edit",
        "#![allow(dead_code)]",
        "",
        "use crate::frame::{expect_len, read_u32, DecodeError};",
        "use crate::x12_surface::DecodedSurfaceRequest;",
        "",
    ]
    for name, fields in FIXED_DECODE.items():
        body_len = sum(4 for _ in fields)  # all u32 in FIXED_DECODE
        fn = f"decode_{name.lower()}"
        lines.append(f"pub fn {fn}(body: &[u8]) -> Result<DecodedSurfaceRequest, DecodeError> {{")
        lines.append(f"    expect_len(body, {body_len})?;")
        for i, (fname, _ty) in enumerate(fields):
            lines.append(f"    let {fname} = read_u32(body, {i * 4})?;")
        if name == "SelectInput":
            lines.append("    if event_mask & !0b111 != 0 {")
            lines.append('        return Err(DecodeError::InvalidField("event_mask"));')
            lines.append("    }")
        if name == "ImportSyncobj":
            # FD count checked by caller
            pass
        variant_fields = ", ".join(f[0] for f in fields)
        lines.append(f"    Ok(DecodedSurfaceRequest::{name} {{ {variant_fields} }})")
        lines.append("}")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    tree = ET.parse(XML)
    root = tree.getroot()
    ns = ""
    if root.tag.startswith("{"):
        ns = root.tag.split("}")[0] + "}"

    reqs = []
    for req in root.findall(f"{ns}request"):
        name = req.attrib["name"]
        opcode = int(req.attrib["opcode"])
        reqs.append((name, opcode, request_size(req)))

    CANON = {
        "QueryVersion": 12,
        "QueryCapabilities": 8,
        "QueryModifiers": 12,
        "CreateSurface": 72,
        "DestroySurface": 8,
        "ImportSyncobj": 12,
        "FreeSyncobj": 8,
        "Attach": 12,
        "Detach": 8,
        "Present": 88,
        "SelectInput": 16,
    }

    rs = [
        "// @generated by safe/x12-proto/tools/gen_wire.py — do not edit",
        "#![allow(dead_code)]",
        "",
        "#[repr(u8)]",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub enum SurfaceOp {",
    ]
    for name, opcode, _ in reqs:
        rs.append(f"    {name} = {opcode},")
    rs += ["}", "", "pub mod sizes {"]
    for name, _, _ in reqs:
        sz = CANON.get(name)
        if sz is None:
            continue
        rs.append(f"    pub const {name.upper()}: usize = {sz};")
    rs += ["}", ""]

    h = [
        "/* @generated by safe/x12-proto/tools/gen_wire.py — do not edit */",
        "#ifndef X12_PROTO_GENERATED_H",
        "#define X12_PROTO_GENERATED_H",
        "",
    ]
    for name, opcode, _ in reqs:
        h.append(f"#define X12_PROTO_OP_{name.upper()} {opcode}")
    h.append("")
    for name, _, _ in reqs:
        sz = CANON.get(name)
        if sz is None:
            continue
        h.append(f"#define X12_PROTO_GEN_SZ_{name.upper()} {sz}")
    h += ["", "#endif", ""]

    OUT_RS.parent.mkdir(parents=True, exist_ok=True)
    OUT_RS.write_text("\n".join(rs) + "\n")
    OUT_H.write_text("\n".join(h) + "\n")
    OUT_DECODE.write_text(emit_decode_rs())
    print(f"wrote {OUT_RS.relative_to(ROOT)}")
    print(f"wrote {OUT_DECODE.relative_to(ROOT)}")
    print(f"wrote {OUT_H.relative_to(ROOT)}")

    bad = 0
    for name, _, computed in reqs:
        if name not in CANON:
            continue
        if name in (
            "QueryVersion",
            "QueryCapabilities",
            "QueryModifiers",
            "DestroySurface",
            "ImportSyncobj",
            "FreeSyncobj",
            "Attach",
            "Detach",
            "SelectInput",
        ):
            if computed != CANON[name]:
                print(
                    f"WARN size mismatch {name}: xml~={computed} canon={CANON[name]}",
                    file=sys.stderr,
                )
                bad += 1
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
