#!/usr/bin/env python3
"""Generate wire size/opcode constants from proto/xcb/src/x12_surface.xml.

ADR-0016: XML is the source of truth; Rust/C sizes must not drift by hand.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[3]
XML = ROOT / "proto/xcb/src/x12_surface.xml"
OUT_RS = ROOT / "safe/x12-proto/src/generated_wire.rs"
OUT_H = ROOT / "safe/x12-proto/include/x12_proto_generated.h"

# Field sizes matching xcbgen / X wire (bytes)
TYPE_SIZE = {
    "CARD8": 1,
    "INT8": 1,
    "BYTE": 1,
    "BOOL": 1,
    "CARD16": 2,
    "INT16": 2,
    "CARD32": 4,
    "INT32": 4,
    "CARD64": 8,
    "INT64": 8,
    "WINDOW": 4,
    "DRAWABLE": 4,
    "SURFACE": 4,
    "SYNCOBJ": 4,
    "EVENT": 4,
    "ATOM": 4,
    "PIXMAP": 4,
}


def align(n: int, a: int) -> int:
    return (n + a - 1) // a * a


def request_size(req: ET.Element) -> int:
    # major + minor + length = 4; then fields
    size = 4
    for child in list(req):
        tag = child.tag.split("}")[-1]
        if tag == "field":
            t = child.attrib["type"]
            size = align(size, TYPE_SIZE.get(t, 4) if t in ("CARD64", "INT64") else 1)
            # natural align for 2/4/8
            sz = TYPE_SIZE.get(t)
            if sz is None:
                sz = 4
            if sz >= 2:
                size = align(size, min(sz, 4) if sz < 8 else 8)
            size += sz
        elif tag == "pad":
            size += int(child.attrib.get("bytes", 0))
        elif tag == "fd":
            pass  # SCM_RIGHTS, not in byte length
        elif tag == "list":
            # variable — skip fixed size
            pass
        elif tag == "required_start_align":
            a = int(child.attrib.get("align", 4))
            size = align(size, a)
    # request length is in 4-byte units; pad to 4
    return align(size, 4)


def main() -> int:
    tree = ET.parse(XML)
    root = tree.getroot()
    ns = ""
    if root.tag.startswith("{"):
        ns = root.tag.split("}")[0] + "}"

    reqs = []
    for req in root.findall(f"{ns}request"):
        name = req.attrib["name"]
        opcode = int(req.attrib["opcode"])
        # Prefer hand-maintained sizes when list/fd make XML sizing ambiguous.
        # We still emit opcodes from XML.
        reqs.append((name, opcode, request_size(req)))

    # Canonical sizes from XCB/hand ABI (must match drift_check)
    CANON = {
        "QueryVersion": 12,
        "QueryCapabilities": 8,
        "QueryModifiers": 12,
        "CreateSurface": 72,
        "DestroySurface": 8,
        "ImportSyncobj": 12,
        "FreeSyncobj": 8,
        "Attach": 12,
        "Detach": 8,
        "Present": 88,
        "SelectInput": 16,
    }

    rs = [
        "// @generated by safe/x12-proto/tools/gen_wire.py — do not edit",
        "#![allow(dead_code)]",
        "",
        "#[repr(u8)]",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub enum SurfaceOp {",
    ]
    for name, opcode, _ in reqs:
        rs.append(f"    {name} = {opcode},")
    rs += ["}", "", "pub mod sizes {"]
    for name, _, _ in reqs:
        sz = CANON.get(name)
        if sz is None:
            continue
        rs.append(f"    pub const {name.upper()}: usize = {sz};")
    rs += ["}", ""]

    h = [
        "/* @generated by safe/x12-proto/tools/gen_wire.py — do not edit */",
        "#ifndef X12_PROTO_GENERATED_H",
        "#define X12_PROTO_GENERATED_H",
        "",
    ]
    for name, opcode, _ in reqs:
        h.append(f"#define X12_PROTO_OP_{name.upper()} {opcode}")
    h.append("")
    for name, _, _ in reqs:
        sz = CANON.get(name)
        if sz is None:
            continue
        h.append(f"#define X12_PROTO_GEN_SZ_{name.upper()} {sz}")
    h += ["", "#endif", ""]

    OUT_RS.parent.mkdir(parents=True, exist_ok=True)
    OUT_RS.write_text("\n".join(rs) + "\n")
    OUT_H.write_text("\n".join(h) + "\n")
    print(f"wrote {OUT_RS.relative_to(ROOT)}")
    print(f"wrote {OUT_H.relative_to(ROOT)}")

    # Verify XML-derived sizes match canon when computable
    bad = 0
    for name, _, computed in reqs:
        if name not in CANON:
            continue
        # CreateSurface/Present have lists/pads that our naive walker may mis-size;
        # only enforce for simple fixed requests.
        if name in (
            "QueryVersion",
            "QueryCapabilities",
            "QueryModifiers",
            "DestroySurface",
            "ImportSyncobj",
            "FreeSyncobj",
            "Attach",
            "Detach",
            "SelectInput",
        ):
            if computed != CANON[name]:
                print(
                    f"WARN size mismatch {name}: xml~={computed} canon={CANON[name]}",
                    file=sys.stderr,
                )
                bad += 1
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
