// @generated by safe/x12-proto/tools/gen_wire.py — do not edit
#![allow(dead_code)]

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SurfaceOp {
    QueryVersion = 0,
    QueryCapabilities = 1,
    QueryModifiers = 2,
    CreateSurface = 3,
    DestroySurface = 4,
    ImportSyncobj = 5,
    FreeSyncobj = 6,
    Attach = 7,
    Detach = 8,
    Present = 9,
    SelectInput = 10,
}

pub mod sizes {
    pub const QUERYVERSION: usize = 12;
    pub const QUERYCAPABILITIES: usize = 8;
    pub const QUERYMODIFIERS: usize = 12;
    pub const CREATESURFACE: usize = 72;
    pub const DESTROYSURFACE: usize = 8;
    pub const IMPORTSYNCOBJ: usize = 12;
    pub const FREESYNCOBJ: usize = 8;
    pub const ATTACH: usize = 12;
    pub const DETACH: usize = 8;
    pub const PRESENT: usize = 88;
    pub const SELECTINPUT: usize = 16;
}

