// @generated by safe/x12-proto/tools/gen_wire.py — do not edit
#![allow(dead_code)]

use crate::frame::{expect_len, read_u32, DecodeError};
use crate::x12_surface::DecodedSurfaceRequest;

pub fn decode_queryversion(body: &[u8]) -> Result<DecodedSurfaceRequest, DecodeError> {
    expect_len(body, 8)?;
    let major_version = read_u32(body, 0)?;
    let minor_version = read_u32(body, 4)?;
    Ok(DecodedSurfaceRequest::QueryVersion { major_version, minor_version })
}

pub fn decode_querycapabilities(body: &[u8]) -> Result<DecodedSurfaceRequest, DecodeError> {
    expect_len(body, 4)?;
    let drawable = read_u32(body, 0)?;
    Ok(DecodedSurfaceRequest::QueryCapabilities { drawable })
}

pub fn decode_querymodifiers(body: &[u8]) -> Result<DecodedSurfaceRequest, DecodeError> {
    expect_len(body, 8)?;
    let drawable = read_u32(body, 0)?;
    let format = read_u32(body, 4)?;
    Ok(DecodedSurfaceRequest::QueryModifiers { drawable, format })
}

pub fn decode_destroysurface(body: &[u8]) -> Result<DecodedSurfaceRequest, DecodeError> {
    expect_len(body, 4)?;
    let surface = read_u32(body, 0)?;
    Ok(DecodedSurfaceRequest::DestroySurface { surface })
}

pub fn decode_importsyncobj(body: &[u8]) -> Result<DecodedSurfaceRequest, DecodeError> {
    expect_len(body, 8)?;
    let syncobj = read_u32(body, 0)?;
    let drawable = read_u32(body, 4)?;
    Ok(DecodedSurfaceRequest::ImportSyncobj { syncobj, drawable })
}

pub fn decode_freesyncobj(body: &[u8]) -> Result<DecodedSurfaceRequest, DecodeError> {
    expect_len(body, 4)?;
    let syncobj = read_u32(body, 0)?;
    Ok(DecodedSurfaceRequest::FreeSyncobj { syncobj })
}

pub fn decode_attach(body: &[u8]) -> Result<DecodedSurfaceRequest, DecodeError> {
    expect_len(body, 8)?;
    let window = read_u32(body, 0)?;
    let surface = read_u32(body, 4)?;
    Ok(DecodedSurfaceRequest::Attach { window, surface })
}

pub fn decode_detach(body: &[u8]) -> Result<DecodedSurfaceRequest, DecodeError> {
    expect_len(body, 4)?;
    let window = read_u32(body, 0)?;
    Ok(DecodedSurfaceRequest::Detach { window })
}

pub fn decode_selectinput(body: &[u8]) -> Result<DecodedSurfaceRequest, DecodeError> {
    expect_len(body, 12)?;
    let eid = read_u32(body, 0)?;
    let window = read_u32(body, 4)?;
    let event_mask = read_u32(body, 8)?;
    if event_mask & !0b111 != 0 {
        return Err(DecodeError::InvalidField("event_mask"));
    }
    Ok(DecodedSurfaceRequest::SelectInput { eid, window, event_mask })
}

